# .github/workflows/dotnet-ci.yml
name: .NET Build and Test

on:
  push:
    branches: main 
  pull_request:
    branches: main 

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  # Change based on your .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
